import { useRef, useState, useEffect } from 'react'
import { FileText, FileSpreadsheet, Image as ImageIcon, File } from 'lucide-react'
import { sendMsg, stopMsg } from '../../API/Msg'
import { uploadFile, deleteFileFromRAG } from '../../API/File'
import { renameChat } from '../../API/Chat' 
import { useChatStore } from '../../Context/ChatContext'
import { usePython } from './usePython'

export const useSendMessage = (chatId: string) => {
  const [input, setInput] = useState('')
  const { getMessages, setMessages, appendMessage, appendToken, updateMessage, removeMessage, isLoading, setLoading } = useChatStore()
  const { runCode, isReady: isPythonReady } = usePython()

  const abortControllerRef = useRef<AbortController | null>(null)
  const [uploading, setUploading] = useState(false)
  const currentFileName = useRef<string | null>(null)
  const loading = isLoading(chatId)

  // File Attachment & Staging States
  const [pendingFile, setPendingFile] = useState<File | null>(null)
  const [previewUrl, setPreviewUrl] = useState<string | null>(null)

  // Object URL cleanup
  useEffect(() => {
    return () => {
      if (previewUrl) URL.revokeObjectURL(previewUrl)
    }
  }, [previewUrl])

  const clearStaging = () => {
    setPendingFile(null)
    if (previewUrl) {
      URL.revokeObjectURL(previewUrl)
      setPreviewUrl(null)
    }
  }

  const stopGeneration = async () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort()
      abortControllerRef.current = null
    }
    if (uploading && currentFileName.current) {
      try {
        await deleteFileFromRAG(currentFileName.current)
      } catch (err) {
        console.error("Cleanup error:", err)
      } finally {
        setUploading(false)
        currentFileName.current = null
      }
      return 
    }
    try {
      await stopMsg(chatId)
    } catch (err) {
      console.error("Stop error:", err)
    } finally {
      setLoading(chatId, false)
    }
  }

  const handleFileUpload = async (file: File, onUploaded: (data: any) => void) => {
    if (!file || !chatId || uploading || loading) return
    setUploading(true)
    currentFileName.current = file.name
    abortControllerRef.current = new AbortController()
    try {
      const res = await uploadFile(file, chatId, abortControllerRef.current.signal)
      if (res.data) onUploaded(res.data)
    } catch (err: any) {
      if (err.name !== 'AbortError' && err.name !== 'CanceledError') {
        console.error(err)
      }
    } finally {
      setUploading(false)
      currentFileName.current = null
      abortControllerRef.current = null
    }
  }

  const sendMessage = async (forcedContent?: string) => {
    const content = forcedContent || input.trim()
    if (!content && !forcedContent) return

    if (!forcedContent) setInput('')
    setLoading(chatId, true)
    abortControllerRef.current = new AbortController()
    const streamingId = crypto.randomUUID()
    const targetChatId = chatId 

    try {
      await sendMsg(
        targetChatId,
        content,
        (token) => appendToken(targetChatId, streamingId, token),
        (userMsg) => appendMessage(targetChatId, userMsg),
        async (assistantMsg) => {
          updateMessage(targetChatId, streamingId, assistantMsg)
          if (targetChatId === chatId) setLoading(chatId, false)

          const history = getMessages(targetChatId)
          const assistantResponses = history.filter(m => m.role === 'assistant')

          if (assistantResponses.length <= 1) {
            const firstUserMsg = history.find(m => m.role === 'user')
            const titleSource = firstUserMsg ? firstUserMsg.content : content
            
            const firstLine = titleSource.split('\n')[0].trim()
            const autoGeneratedTitle = firstLine.length > 28 ? firstLine.slice(0, 25) + '...' : firstLine
            
            try {
              await renameChat(targetChatId, autoGeneratedTitle)
              window.dispatchEvent(new CustomEvent('chat-auto-renamed', {
                detail: { chatId: targetChatId, title: autoGeneratedTitle }
              }))
            } catch (renameError) {
              console.error("Failed to automatically update chat title:", renameError)
            }
          }
        },
        () => {
          removeMessage(targetChatId, streamingId)
          if (targetChatId === chatId) setLoading(chatId, false)
        },
        abortControllerRef.current.signal 
      )
    } catch (err: any) {
      if (err.name !== 'AbortError') console.error(err)
      setLoading(chatId, false)
    }
  }

  // Sequenced Send Process Manager
  const handleSendAction = async () => {
    if (pendingFile) {
      const fileToUpload = pendingFile
      const cachedInput = input.trim()
      
      clearStaging()

      await handleFileUpload(fileToUpload, (data) => {
        setMessages(chatId, [...getMessages(chatId), data])
      })

      if (cachedInput) {
        sendMessage(cachedInput)
      }
    } else if (input.trim()) {
      sendMessage()
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSendAction()
    }
  }

  const handlePaste = (e: React.ClipboardEvent<HTMLTextAreaElement>) => {
    const items = e.clipboardData.items
    for (let i = 0; i < items.length; i++) {
      if (items[i].type.indexOf('image') !== -1) {
        const file = items[i].getAsFile()
        if (file) {
          e.preventDefault()
          setPendingFile(file)
          setPreviewUrl(URL.createObjectURL(file))
          break
        }
      }
    }
  }

  const onFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    setPendingFile(file)
    setPreviewUrl(URL.createObjectURL(file))
  }

  // File presentation helpers
  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return '0 B'
    const k = 1024
    const sizes = ['B', 'KB', 'MB', 'GB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i]
  }

  const getFileIcon = (ext: string) => {
    const e = ext.toLowerCase()
    if (['.pdf', '.doc', '.docx', '.txt', '.md'].includes(e)) return FileText({ size: 18, className: "text-blue-500" })
    if (['.csv', '.xlsx', '.xls'].includes(e)) return FileSpreadsheet({ size: 18, className: "text-green-500" })
    if (['.jpg', '.jpeg', '.png', '.gif', '.webp'].includes(e)) return ImageIcon({ size: 18, className: "text-purple-500" })
    return File({ size: 18, className: "text-gray-400" })
  }

  const getFileColor = (ext: string) => {
    const e = ext.toLowerCase()
    if (['.pdf'].includes(e)) return 'border-red-200 dark:border-red-500/20 bg-red-50 dark:bg-red-500/5'
    if (['.doc', '.docx', '.txt', '.md'].includes(e)) return 'border-blue-200 dark:border-blue-500/20 bg-blue-50 dark:bg-blue-500/5'
    if (['.csv', '.xlsx', '.xls'].includes(e)) return 'border-green-200 dark:border-green-500/20 bg-green-50 dark:bg-green-500/5'
    if (['.jpg', '.jpeg', '.png', '.gif', '.webp'].includes(e)) return 'border-purple-200 dark:border-purple-500/20 bg-purple-50 dark:bg-purple-500/5'
    return 'border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800'
  }

  const formatTime = (date: string) =>
    new Date(date).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })

  return { 
    input, setInput, sendMessage, stopGeneration, handleFileUpload, loading, uploading, runCode, isPythonReady,
    pendingFile, previewUrl, clearStaging, handleSendAction, handleKeyDown, 
    handlePaste, onFileSelect, formatFileSize, getFileIcon, getFileColor, formatTime
  }
}